### PR TITLE
Convert entity to scriptID in native calls

### PR DESCRIPTION
**Pull request by LeonMrBonnie**

### CODE REVIEW

**Comment by vadzz-dev** [comment]
That's kinda questionable if we should do. Calling V8ResourceImpl::Get & V8Entity::Get for each argument would decrease a performance

**Comment by LeonMrBonnie** [comment]
I changed it a bit so it should be better for performance now. It now only gets the resource once, and only gets the entity for the INT32 type.
Imo, this is now fine. V8Entity::Get shouldn't be that expensive, as it only gets an internal field and casts it.

**Review by jovanivanovic — APPROVED** [review]
This is very helpful for new developers coming to alt:V. Every now and then someone complains how passing a player reference doesn't work in natives.

**Comment by FabianTerhorst** [comment]
It decreases the performance of natives that needs a int. So im against it as well.

**Comment by jovanivanovic** [comment]
Well, that settles it.

**Comment by LeonMrBonnie** [comment]
Maybe we should make a benchmark first and decide then, if its an unsignificant amount we shouldn't just discard this.
Looking at the code I also realized this could be optimized even more by just checking for the type of the passed value, so if the type of the passed value is an object THEN get the entity associated with it. That would mean that it would add only 1 additional check (for the type of the value) for every int argument, if its not an entity. And checking for the type of the Value is really fast.

edit:
I also benchmarked the `IsObject` method, and calling it 10.000 times takes about 0,02ms.

**Comment by Unnvaldr** [comment]
I think you should make that edge case checked last, if any other conditions fail

**Comment by LeonMrBonnie** [comment]
> 
> 
> I think you should make that edge case checked last, if any other conditions fail

In terms of performance it would make absolutely no difference, and it would make the code a bit uglier because I couldn't have that `V8Entity::Get` check right in the if statement.
How it is right now, should be fine.

**Review by FabianTerhorst — APPROVED** [review]

**Pull request merged**
