### PR TITLE
Add clientjs command to show general info

### PR DESCRIPTION
**Pull request by LeonMrBonnie**
grafik

### CODE REVIEW

**Comment by jovanivanovic** [comment]
To be honest I don't see use for this command.

**Comment by LeonMrBonnie** [comment]
> 
> 
> To be honest I don't see use for this command.

It is just a command to display small information about the module, just like the `js-module` command of the serverside JS module.

**Comment by jovanivanovic** [comment]
In that case at least make it the same as it is on the server

**Comment by LeonMrBonnie** [comment]
> 
> 
> In that case at least make it the same as it is on the server

Just the name of the command or copy the whole behaviour of the command too?

**Comment by jovanivanovic** [comment]
> Just the name of the command or copy the whole behaviour of the command too?

Both.

**Comment by vadzz-dev** [comment]
Can we change `client js module` to `js-module`?

**Comment by LeonMrBonnie** [comment]
> 
> 
> Can we change `client js module` to `js-module`?

Already done.
The command now behaves exactly like on serverside, just that it shows sdk version instead of module version, and v8 version instead of nodejs version.

**Review by jovanivanovic — APPROVED** [review]

**Pull request merged**
