### PR TITLE
Add new export and adapt old export

### PR DESCRIPTION
**Pull request by LeonMrBonnie**

### CODE REVIEW

**Comment by vadzz-dev** [comment]
Lets use ICore::RegisterScriptRuntime instead

**Comment by LeonMrBonnie** [comment]
Alright, this is a draft then until it is changed in the CPP SDK.

**Comment by vadzz-dev** [comment]
I looked in the client code and RegisterScriptRuntime should work, can you test it?

**Comment by LeonMrBonnie** [comment]
Just change the return value and instead of returning the script runtime register it, or do I also need to change the exported function name to altMain like on serverside?

**Comment by LeonMrBonnie** [comment]
Okay so I tried using RegisterScriptRuntime on client and it works well.
So we should now delete the needed `GetType` export from the module (you specify the type in the RegisterScriptRuntime call)
Then we can change the module to use RegisterScriptRuntime instead.

**Comment by vadzz-dev** [comment]
Shouldn't it be marked as a draft till sdk gets required changes?

**Comment by LeonMrBonnie** [comment]
How I changed it still works, when its updated in SDK we would only need to remove the GetType export then, but I can mark it as draft for now

**Review by drakeee — APPROVED** [review]

**Review by vadzz-dev — APPROVED** [review]

**Pull request merged**
