### PR TITLE
Add streamedIn getter

### PR DESCRIPTION
**Pull request by LeonMrBonnie**
The performance with this should be fine, as there will never be more than 128 entities in stream range at once anyway.

### CODE REVIEW

**Review by jovanivanovic — APPROVED** [review]

**Comment by FabianTerhorst** [comment]
I would prefer a std map here. So that the delete doesn't need O(n) by 128 players. Not sure how much difference it would make.

**Comment by LeonMrBonnie** [comment]
> 
> 
> I would prefer a std map here. So that the delete doesn't need O(n) by 128 players. Not sure how much difference it would make.

Map with ID as key and the Entity as value?

**Comment by FabianTerhorst** [comment]
Yes thats what i meant

**Comment by LeonMrBonnie** [comment]
@FabianTerhorst Should be fine now

**Comment by FabianTerhorst** [comment]
Wouldnt it be possible to use v8::map so that conversion in the getter isnt needed.

**Comment by LeonMrBonnie** [comment]
> 
> 
> Wouldnt it be possible to use v8::map so that conversion in the getter isnt needed.

A v8 map is much slower than a C++ map.
Also, the `GetOrCreateEntity` does nothing else than accessing another C++ map to get the underlying stored entity, so it's very fast.

**Pull request merged**
